data:
  train_path: '/root/maize'
  split_dir: '/root/DiffTreeVxl/dataset/maize'
  img_size: 256

network:
  voxel_output: 64
  base_channels: 64
  dim_mults: [1,2,4,8,16]
  dropout: 0.1
  img_backbone: 'unconditioned'
  img_backbone_dim: 768
  with_attention: False

results:
  results_folder: './results'
  save_top_k: 0
  save_last: True

train:
  devices: [0,1,2,3]
  batch_size: 2
  lr: 1.0e-3
  optimizier: "adam"
  scheduler: "CosineAnnealingLR"
  training_epoch: 120
  ema_rate: 0.99
  gradient_clip_val: 1.0
  noise_schedule: "cosine"
  debug: False

wandb:
  wandb_key: "bb015301117aa9f19540d12a3809b714297c11f9"

logging:
  save_dir: './logs'

verbose: False
seed: 666